# Generated by Django 4.1.7 on 2023-04-17 08:51

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("pulpanalytics", "0001_initial"),
        ("pulpanalytics", "0002_system_first_seen"),
        ("pulpanalytics", "0003_system_unique_system_checkin_per_day"),
        ("pulpanalytics", "0004_alter_dailysummary_summary"),
        ("pulpanalytics", "0005_system_postgresql_version"),
        ("pulpanalytics", "0006_system_custom_access_policies_system_custom_roles_and_more"),
        ("pulpanalytics", "0007_alter_system_postgresql_version"),
        ("pulpanalytics", "0008_DATA_fix_rbac_stats"),
        ("pulpanalytics", "0009_remove_onlineworkers_system_system_content_app_hosts_and_more"),
        ("pulpanalytics", "0010_remove_dailysummary_id_alter_dailysummary_date"),
        ("pulpanalytics", "0010_postgresversioncount"),
        ("pulpanalytics", "0012_deploymentstats"),
        ("pulpanalytics", "0013_postgresversioncount_pulpanalyti_summary_3ad8a0_idx"),
        ("pulpanalytics", "0014_xyzversioncount_xyversioncount_and_more"),
        ("pulpanalytics", "0015_alter_component_unique_together_and_more"),
        ("pulpanalytics", "0016_agecount_agecount_pulpanalyti_summary_e1ed61_idx_and_more"),
        ("pulpanalytics", "0017_numbercount_and_more"),
        ("pulpanalytics", "0018_remove_dailysummary_summary"),
        ("pulpanalytics", "0019_alter_agecount_unique_together_and_more"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="System",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("system_id", models.UUIDField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("first_seen", models.DateTimeField()),
                ("groups", models.PositiveIntegerField(null=True)),
                ("users", models.PositiveIntegerField(null=True)),
                ("postgresql_version", models.PositiveIntegerField(default=0)),
                ("content_app_hosts", models.PositiveIntegerField(null=True)),
                ("content_app_processes", models.PositiveIntegerField(null=True)),
                ("worker_hosts", models.PositiveIntegerField(null=True)),
                ("worker_processes", models.PositiveIntegerField(null=True)),
                ("custom_access_policies", models.PositiveIntegerField(null=True)),
                ("custom_roles", models.PositiveIntegerField(null=True)),
                ("domains", models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DailySummary",
            fields=[
                ("date", models.DateField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name_plural": "daily summaries",
            },
        ),
        migrations.CreateModel(
            name="DeploymentStats",
            fields=[
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="pulpanalytics.dailysummary",
                    ),
                ),
                ("online_worker_hosts_avg", models.FloatField(blank=True, null=True)),
                ("online_worker_processes_avg", models.FloatField(blank=True, null=True)),
                ("online_content_app_hosts_avg", models.FloatField(blank=True, null=True)),
                ("online_content_app_processes_avg", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AgeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.system"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostgresVersionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XYVersionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XYZVersionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NumberCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("number", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="postgresversioncount",
            index=models.Index(fields=["summary"], name="pulpanalyti_summary_3ad8a0_idx"),
        ),
        migrations.AddIndex(
            model_name="xyversioncount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_0f49bd_idx"),
        ),
        migrations.AddIndex(
            model_name="agecount",
            index=models.Index(fields=["summary"], name="pulpanalyti_summary_e1ed61_idx"),
        ),
        migrations.AddIndex(
            model_name="xyzversioncount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_339cee_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["name"], name="pulpanalyti_name_459b73_idx"),
        ),
        migrations.AddIndex(
            model_name="numbercount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_c5d7a9_idx"),
        ),
        migrations.AddConstraint(
            model_name="system",
            constraint=models.UniqueConstraint(
                models.F("system_id"),
                django.db.models.functions.datetime.TruncDay("created"),
                name="unique_system_checkin_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="agecount",
            constraint=models.UniqueConstraint(
                models.F("summary"), models.F("age"), name="pulpanalytics_agecount_uniquenes"
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                models.F("system"), models.F("name"), name="pulpanalytics_component_uniquenes"
            ),
        ),
        migrations.AddConstraint(
            model_name="numbercount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("number"),
                name="pulpanalytics_numbercount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="postgresversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("version"),
                name="pulpanalytics_postgresversioncount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="xyversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("version"),
                name="pulpanalytics_xyversioncount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="xyzversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("version"),
                name="pulpanalytics_xyzversioncount_uniquenes",
            ),
        ),
    ]
