# Generated by Django 4.0.8 on 2022-10-30 08:24

import django.db.models.expressions
import django.db.models.functions.datetime
from django.db import migrations, models


def remove_duplicates(apps, schema_editor):
    System = apps.get_model("pulpanalytics", "system")
    first_pks_by_day = (
        System.objects.annotate(
            created_day=django.db.models.functions.TruncDay("created"),
            first_pk_by_day=django.db.models.Window(
                expression=django.db.models.functions.FirstValue("pk"),
                partition_by=[django.db.models.F("system_id"), django.db.models.F("created_day")],
                order_by=django.db.models.F("created").asc(),
            ),
        )
        .values("first_pk_by_day")
        .distinct()
    )
    System.objects.exclude(pk__in=first_pks_by_day).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("pulpanalytics", "0002_system_first_seen"),
    ]

    operations = [
        migrations.RunPython(code=remove_duplicates, reverse_code=migrations.RunPython.noop),
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE", reverse_sql=migrations.RunSQL.noop
        ),  # Flush pending tirggers
        migrations.AddConstraint(
            model_name="system",
            constraint=models.UniqueConstraint(
                django.db.models.expressions.F("system_id"),
                django.db.models.functions.datetime.TruncDay("created"),
                name="unique_system_checkin_per_day",
            ),
        ),
    ]
