# Generated by Django 4.0.8 on 2022-10-14 08:11

from django.db import migrations
import pulpanalytics.fields
import pulpanalytics.summary_pb2


class Migration(migrations.Migration):

    dependencies = [
        ('pulpanalytics', '0003_system_unique_system_checkin_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysummary',
            name='summary',
            field=pulpanalytics.fields.ProtoBufField(serializer=pulpanalytics.summary_pb2.Summary),
        ),
    ]
