# Generated by Django 4.0.6 on 2022-11-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0004_alter_dailysummary_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="postgresql_version",
            field=models.PositiveIntegerField(default=0),  # The protobuf default for uint32
            preserve_default=False,
        ),
    ]
