# Generated by Django 4.1.7 on 2023-03-07 15:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0005_system_postgresql_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="system",
            name="custom_access_policies",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="custom_roles",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="domains",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="groups",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="system",
            name="users",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
