# Generated by Django 4.1.7 on 2023-03-08 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0006_system_custom_access_policies_system_custom_roles_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="system",
            name="postgresql_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
