# Generated by Django 4.1.7 on 2023-03-17 07:04

from django.db import migrations


def fix_collected_rbac_stats(apps, schema):
    # Delete all the 0s from Systems that never reported rbac_stats
    System = apps.get_model("pulpanalytics", "System")
    Component = apps.get_model("pulpanalytics", "Component")
    component_qs = (
        Component.objects.filter(name="core")
        .exclude(version__startswith="3.23")
        .exclude(version__startswith="3.24")
    )
    System.objects.filter(component__in=component_qs).update(
        users=None, groups=None, domains=None, custom_access_policies=None, custom_roles=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0007_alter_system_postgresql_version"),
    ]

    operations = [
        migrations.RunPython(
            code=fix_collected_rbac_stats, reverse_code=migrations.RunPython.noop, elidable=True
        ),
    ]
