# Generated by Django 4.1.7 on 2023-04-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0009_remove_onlineworkers_system_system_content_app_hosts_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailysummary",
            name="id",
        ),
        migrations.AlterField(
            model_name="dailysummary",
            name="date",
            field=models.DateField(primary_key=True, serialize=False),
        ),
    ]
