# Generated by Django 4.1.7 on 2023-04-06 11:49

import django.db.models.deletion
from django.db import migrations, models


def move_deployment_stats_data_up(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    DeploymentStats = apps.get_model("pulpanalytics", "DeploymentStats")
    for ds in DailySummary.objects.all():
        if any(
            [
                ds.summary.online_workers.hosts__avg,
                ds.summary.online_workers.processes__avg,
                ds.summary.online_content_apps.hosts__avg,
                ds.summary.online_content_apps.processes__avg,
            ]
        ):
            DeploymentStats.objects.create(
                summary=ds,
                online_worker_hosts_avg=ds.summary.online_workers.hosts__avg,
                online_worker_processes_avg=ds.summary.online_workers.processes__avg,
                online_content_app_hosts_avg=ds.summary.online_content_apps.hosts__avg,
                online_content_app_processes_avg=ds.summary.online_content_apps.processes__avg,
            )
            ds.summary.ClearField("online_workers")
            ds.summary.ClearField("online_content_apps")
            ds.save()


def move_deployment_stats_data_down(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    for ds in DailySummary.objects.all():
        if hasattr(ds, "deploymentstats"):
            ds.summary.online_workers.hosts__avg = ds.deploymentstats.online_worker_hosts_avg or 0.0
            ds.summary.online_workers.processes__avg = (
                ds.deploymentstats.online_worker_processes_avg or 0.0
            )
            ds.summary.online_content_apps.hosts__avg = (
                ds.deploymentstats.online_content_app_hosts_avg or 0.0
            )
            ds.summary.online_content_apps.processes__avg = (
                ds.deploymentstats.online_content_app_processes_avg or 0.0
            )
            ds.save()
            ds.deploymentstats.delete()


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0010_postgresversioncount"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeploymentStats",
            fields=[
                (
                    "summary",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="pulpanalytics.dailysummary",
                    ),
                ),
                ("online_worker_hosts_avg", models.FloatField(null=True, blank=True)),
                ("online_worker_processes_avg", models.FloatField(null=True, blank=True)),
                ("online_content_app_hosts_avg", models.FloatField(null=True, blank=True)),
                ("online_content_app_processes_avg", models.FloatField(null=True, blank=True)),
            ],
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="SET CONSTRAINTS ALL IMMEDIATE;",
        ),
        migrations.RunPython(
            code=move_deployment_stats_data_up,
            reverse_code=move_deployment_stats_data_down,
            elidable=True,
        ),
    ]
