# Generated by Django 4.1.7 on 2023-04-08 22:33

import django.db.models.deletion
from django.db import migrations, models


def move_version_count_data_up(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    XYVersionCount = apps.get_model("pulpanalytics", "XYVersionCount")
    XYZVersionCount = apps.get_model("pulpanalytics", "XYZVersionCount")
    for ds in DailySummary.objects.all():
        for item in ds.summary.xy_component:
            XYVersionCount.objects.create(
                summary=ds, name=item.name, version=item.version, count=item.count
            )
        for item in ds.summary.xyz_component:
            XYZVersionCount.objects.create(
                summary=ds, name=item.name, version=item.version, count=item.count
            )
        ds.summary.ClearField("xy_component")
        ds.summary.ClearField("xyz_component")
        ds.save()


def move_version_count_data_down(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    XYVersionCount = apps.get_model("pulpanalytics", "XYVersionCount")
    XYZVersionCount = apps.get_model("pulpanalytics", "XYZVersionCount")
    for ds in DailySummary.objects.all():
        for item in XYVersionCount.objects.filter(summary=ds):
            ds.summary.xy_component.add(name=item.name, version=item.version, count=item.count)
        for item in XYZVersionCount.objects.filter(summary=ds):
            ds.summary.xyz_component.add(name=item.name, version=item.version, count=item.count)
        ds.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0013_postgresversioncount_pulpanalyti_summary_3ad8a0_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="XYZVersionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XYVersionCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("version", models.TextField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="xyzversioncount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_339cee_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="xyzversioncount",
            unique_together={("summary", "name", "version")},
        ),
        migrations.AddIndex(
            model_name="xyversioncount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_0f49bd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="xyversioncount",
            unique_together={("summary", "name", "version")},
        ),
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="SET CONSTRAINTS ALL IMMEDIATE;",
            elidable=True,
        ),
        migrations.RunPython(
            code=move_version_count_data_up,
            reverse_code=move_version_count_data_down,
            elidable=True,
        ),
    ]
