# Generated by Django 4.1.7 on 2023-04-14 13:19

import django.db.models.deletion
from django.db import migrations, models


def move_age_count_data_up(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    AgeCount = apps.get_model("pulpanalytics", "AgeCount")
    for ds in DailySummary.objects.all():
        for item in ds.summary.age_count:
            AgeCount.objects.create(summary=ds, age=item.age, count=item.count)
        ds.summary.ClearField("age_count")
        ds.save()


def move_age_count_data_down(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    AgeCount = apps.get_model("pulpanalytics", "AgeCount")
    for ds in DailySummary.objects.all():
        for item in AgeCount.objects.filter(summary=ds):
            ds.summary.age_count.add(age=item.age, count=item.count)
        ds.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0015_alter_component_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AgeCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="agecount",
            index=models.Index(fields=["summary"], name="pulpanalyti_summary_e1ed61_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="agecount",
            unique_together={("summary", "age")},
        ),
        migrations.RunSQL(
            sql="",
            reverse_sql="SET CONSTRAINTS ALL IMMEDIATE;",
        ),
        migrations.RunPython(
            code=move_age_count_data_up,
            reverse_code=move_age_count_data_down,
            elidable=True,
        ),
    ]
