# Generated by Django 4.1.7 on 2023-04-15 11:49

import django.db.models.deletion
from django.db import migrations, models


def move_rbac_count_data_up(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    NumberCount = apps.get_model("pulpanalytics", "NumberCount")
    for ds in DailySummary.objects.all():
        for name in ["users", "groups", "domains", "custom_access_policies", "custom_roles"]:
            for item in getattr(ds.summary.rbac_stats, name):
                NumberCount.objects.create(
                    summary=ds, name=name, number=item.number, count=item.count
                )
        ds.summary.ClearField("rbac_stats")
        ds.save()


def move_rbac_count_data_down(apps, schema_editor):
    DailySummary = apps.get_model("pulpanalytics", "DailySummary")
    NumberCount = apps.get_model("pulpanalytics", "NumberCount")
    for ds in DailySummary.objects.all():
        for item in NumberCount.objects.filter(summary=ds):
            getattr(ds.summary.rbac_stats, item.name).add(number=item.number, count=item.count)
        ds.save()


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0016_agecount_agecount_pulpanalyti_summary_e1ed61_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.TextField()),
                ("number", models.PositiveIntegerField()),
                ("count", models.PositiveIntegerField()),
                (
                    "summary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="pulpanalytics.dailysummary"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="numbercount",
            index=models.Index(fields=["summary", "name"], name="pulpanalyti_summary_c5d7a9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="numbercount",
            unique_together={("summary", "name", "number")},
        ),
        migrations.RunSQL(
            sql=migrations.RunSQL.noop,
            reverse_sql="SET CONSTRAINTS ALL IMMEDIATE;",
            elidable=True,
        ),
        migrations.RunPython(
            code=move_rbac_count_data_up,
            reverse_code=move_rbac_count_data_down,
            elidable=True,
        ),
    ]
