# Generated by Django 4.1.7 on 2023-04-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pulpanalytics", "0018_remove_dailysummary_summary"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="agecount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="component",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="numbercount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="postgresversioncount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="xyversioncount",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="xyzversioncount",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="agecount",
            constraint=models.UniqueConstraint(
                models.F("summary"), models.F("age"), name="pulpanalytics_agecount_uniquenes"
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                models.F("system"), models.F("name"), name="pulpanalytics_component_uniquenes"
            ),
        ),
        migrations.AddConstraint(
            model_name="numbercount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("number"),
                name="pulpanalytics_numbercount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="postgresversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("version"),
                name="pulpanalytics_postgresversioncount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="xyversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("version"),
                name="pulpanalytics_xyversioncount_uniquenes",
            ),
        ),
        migrations.AddConstraint(
            model_name="xyzversioncount",
            constraint=models.UniqueConstraint(
                models.F("summary"),
                models.F("name"),
                models.F("version"),
                name="pulpanalytics_xyzversioncount_uniquenes",
            ),
        ),
    ]
