# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsummary.proto\"\xc5\x03\n\x07Summary\x12\x37\n\x13online_content_apps\x18\x01 \x01(\x0b\x32\x1a.Summary.OnlineContentApps\x12.\n\x0eonline_workers\x18\x02 \x01(\x0b\x32\x16.Summary.OnlineWorkers\x12*\n\x0cxy_component\x18\x03 \x03(\x0b\x32\x14.Summary.XYComponent\x12,\n\rxyz_component\x18\x04 \x03(\x0b\x32\x15.Summary.XYZComponent\x1a?\n\x11OnlineContentApps\x12\x16\n\x0eprocesses__avg\x18\x01 \x01(\x02\x12\x12\n\nhosts__avg\x18\x02 \x01(\x02\x1a;\n\rOnlineWorkers\x12\x16\n\x0eprocesses__avg\x18\x01 \x01(\x02\x12\x12\n\nhosts__avg\x18\x02 \x01(\x02\x1a;\n\x0bXYComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\r\x1a<\n\x0cXYZComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\r')



_SUMMARY = DESCRIPTOR.message_types_by_name['Summary']
_SUMMARY_ONLINECONTENTAPPS = _SUMMARY.nested_types_by_name['OnlineContentApps']
_SUMMARY_ONLINEWORKERS = _SUMMARY.nested_types_by_name['OnlineWorkers']
_SUMMARY_XYCOMPONENT = _SUMMARY.nested_types_by_name['XYComponent']
_SUMMARY_XYZCOMPONENT = _SUMMARY.nested_types_by_name['XYZComponent']
Summary = _reflection.GeneratedProtocolMessageType('Summary', (_message.Message,), {

  'OnlineContentApps' : _reflection.GeneratedProtocolMessageType('OnlineContentApps', (_message.Message,), {
    'DESCRIPTOR' : _SUMMARY_ONLINECONTENTAPPS,
    '__module__' : 'summary_pb2'
    # @@protoc_insertion_point(class_scope:Summary.OnlineContentApps)
    })
  ,

  'OnlineWorkers' : _reflection.GeneratedProtocolMessageType('OnlineWorkers', (_message.Message,), {
    'DESCRIPTOR' : _SUMMARY_ONLINEWORKERS,
    '__module__' : 'summary_pb2'
    # @@protoc_insertion_point(class_scope:Summary.OnlineWorkers)
    })
  ,

  'XYComponent' : _reflection.GeneratedProtocolMessageType('XYComponent', (_message.Message,), {
    'DESCRIPTOR' : _SUMMARY_XYCOMPONENT,
    '__module__' : 'summary_pb2'
    # @@protoc_insertion_point(class_scope:Summary.XYComponent)
    })
  ,

  'XYZComponent' : _reflection.GeneratedProtocolMessageType('XYZComponent', (_message.Message,), {
    'DESCRIPTOR' : _SUMMARY_XYZCOMPONENT,
    '__module__' : 'summary_pb2'
    # @@protoc_insertion_point(class_scope:Summary.XYZComponent)
    })
  ,
  'DESCRIPTOR' : _SUMMARY,
  '__module__' : 'summary_pb2'
  # @@protoc_insertion_point(class_scope:Summary)
  })
_sym_db.RegisterMessage(Summary)
_sym_db.RegisterMessage(Summary.OnlineContentApps)
_sym_db.RegisterMessage(Summary.OnlineWorkers)
_sym_db.RegisterMessage(Summary.XYComponent)
_sym_db.RegisterMessage(Summary.XYZComponent)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMARY._serialized_start=18
  _SUMMARY._serialized_end=471
  _SUMMARY_ONLINECONTENTAPPS._serialized_start=224
  _SUMMARY_ONLINECONTENTAPPS._serialized_end=287
  _SUMMARY_ONLINEWORKERS._serialized_start=289
  _SUMMARY_ONLINEWORKERS._serialized_end=348
  _SUMMARY_XYCOMPONENT._serialized_start=350
  _SUMMARY_XYCOMPONENT._serialized_end=409
  _SUMMARY_XYZCOMPONENT._serialized_start=411
  _SUMMARY_XYZCOMPONENT._serialized_end=471
# @@protoc_insertion_point(module_scope)
