# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: summary.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsummary.proto\"\x93\x04\n\x07Summary\x12\x37\n\x13online_content_apps\x18\x01 \x01(\x0b\x32\x1a.Summary.OnlineContentApps\x12.\n\x0eonline_workers\x18\x02 \x01(\x0b\x32\x16.Summary.OnlineWorkers\x12*\n\x0cxy_component\x18\x03 \x03(\x0b\x32\x14.Summary.XYComponent\x12,\n\rxyz_component\x18\x04 \x03(\x0b\x32\x15.Summary.XYZComponent\x12$\n\tage_count\x18\x05 \x03(\x0b\x32\x11.Summary.AgeCount\x1a?\n\x11OnlineContentApps\x12\x16\n\x0eprocesses__avg\x18\x01 \x01(\x02\x12\x12\n\nhosts__avg\x18\x02 \x01(\x02\x1a;\n\rOnlineWorkers\x12\x16\n\x0eprocesses__avg\x18\x01 \x01(\x02\x12\x12\n\nhosts__avg\x18\x02 \x01(\x02\x1a;\n\x0bXYComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\r\x1a<\n\x0cXYZComponent\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x0f\n\x07version\x18\x02 \x02(\t\x12\r\n\x05\x63ount\x18\x03 \x02(\r\x1a&\n\x08\x41geCount\x12\x0b\n\x03\x61ge\x18\x01 \x02(\r\x12\r\n\x05\x63ount\x18\x02 \x02(\r')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'summary_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _SUMMARY._serialized_start=18
  _SUMMARY._serialized_end=549
  _SUMMARY_ONLINECONTENTAPPS._serialized_start=262
  _SUMMARY_ONLINECONTENTAPPS._serialized_end=325
  _SUMMARY_ONLINEWORKERS._serialized_start=327
  _SUMMARY_ONLINEWORKERS._serialized_end=386
  _SUMMARY_XYCOMPONENT._serialized_start=388
  _SUMMARY_XYCOMPONENT._serialized_end=447
  _SUMMARY_XYZCOMPONENT._serialized_start=449
  _SUMMARY_XYZCOMPONENT._serialized_end=509
  _SUMMARY_AGECOUNT._serialized_start=511
  _SUMMARY_AGECOUNT._serialized_end=549
# @@protoc_insertion_point(module_scope)
